USE collegeDB;

INSERT IGNORE INTO students (name, course, age)
VALUES
    ('John Doe', 'Computer Science', 20),
    ('Jane Smith', 'Business Administration', 22),
    ('Mike Johnson', 'Engineering', 21),
    ('Emily Davis', 'Mathematics', 19),
    ('Sarah Wilson', 'Biology', 23),
    ('Wanjiku Kariuki', 'Information Technology', 21),
    ('Kamau Mwangi', 'Computer Science', 22),
    ('Akinyi Odhiambo', 'Medicine', 24),
    ('Otieno Okoth', 'Law', 23),
    ('Njeri Kimani', 'Business Administration', 20),
    ('Kipchoge Koech', 'Engineering', 25),
    ('Chebet Rotich', 'Nursing', 22),
    ('Mutua Musyoka', 'Economics', 21),
    ('Wambui Nduta', 'Education', 20),
    ('Omondi Onyango', 'Architecture', 24),
    ('Nekesa Wafula', 'Pharmacy', 23),
    ('Kiprono Bett', 'Agriculture', 22),
    ('Adhiambo Atieno', 'Psychology', 21),
    ('Muthoni Njoroge', 'Journalism', 20),
    ('Barasa Wekesa', 'Political Science', 25),
    ('Wanjiru Gachanja', 'Environmental Science', 22),
    ('Korir Langat', 'Civil Engineering', 24),
    ('Akoth Awino', 'Sociology', 21),
    ('Gitau Karanja', 'Mechanical Engineering', 23),
    ('Chemutai Chelimo', 'Biochemistry', 22),
    ('Ochieng Owino', 'Statistics', 20),
    ('Nyambura Wangui', 'Finance', 24),
    ('Kiplagat Kirui', 'Electrical Engineering', 25),
    ('Awuor Adhiambo', 'Public Health', 23),
    ('Maina Kinyanjui', 'Actuarial Science', 22),
    ('Jebet Kimutai', 'Veterinary Medicine', 24),
    ('Onyango Odera', 'Philosophy', 21),
    ('Wairimu Ndungu', 'Hospitality Management', 20),
    ('Tanui Kibet', 'Geology', 23),
    ('Atieno Auma', 'Social Work', 22),
    ('Kipkemboi Chepkwony', 'Forestry', 25),
    ('Wangari Muriuki', 'International Relations', 21),
    ('Omondi Mboya', 'Marketing', 24),
    ('Cheptoo Jepkoech', 'Food Science', 22),
    ('Kamau Ngugi', 'Software Engineering', 23),
    ('Achieng Apiyo', 'Anthropology', 20),
    ('Rono Kiprotich', 'Mining Engineering', 25),
    ('Nyokabi Githinji', 'Graphic Design', 21),
    ('Wesonga Wafula', 'History', 22),
    ('Jemutai Chepkorir', 'Chemistry', 24),
    ('Kariuki Kamau', 'Physics', 23),
    ('Awuor Omondi', 'Linguistics', 21),
    ('Kiptoo Sang', 'Telecommunications', 25),
    ('Njambi Waititu', 'Human Resource Management', 22),
    ('Ouko Odhiambo', 'Supply Chain Management', 24);